# Generated by Django 4.0.6 on 2023-04-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QPaperGeneration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpattern',
            name='co',
            field=models.IntegerField(default=0),
        ),
    ]
