# Generated by Django 5.2 on 2025-04-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QPaperGeneration', '0002_qpattern_co'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qpattern',
            name='co',
        ),
        migrations.AddField(
            model_name='qpattern',
            name='co_alignment',
            field=models.CharField(choices=[('Weak', 'Weak'), ('Moderate', 'Moderate'), ('Strong', 'Strong')], default='Moderate', max_length=10),
        ),
        migrations.AddField(
            model_name='qpattern',
            name='importance',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='qpattern',
            name='answer',
            field=models.TextField(blank=True, default='N/A'),
        ),
        migrations.AlterField(
            model_name='qpattern',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10),
        ),
        migrations.AlterField(
            model_name='qpattern',
            name='imgurl',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
