# Generated by Django 5.2 on 2025-04-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QPaperGeneration', '0003_remove_qpattern_co_qpattern_co_alignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qpattern',
            name='co_alignment',
        ),
        migrations.RemoveField(
            model_name='qpattern',
            name='importance',
        ),
        migrations.AddField(
            model_name='qpattern',
            name='co',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='qpattern',
            name='difficulty',
            field=models.IntegerField(default=1),
        ),
    ]
